---
    name: just debug steps of execution
    on:
      push:
    
    jobs:
      test:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 1
          - uses: ./